name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd lambda  # Navega para o diretório lambda
          npm install
          
      - name: Build TypeScript
        run: |
          cd lambda  # Certifica-se de estar no diretório lambda
          npm run build

      - name: Deploy to AWS Lambda
        run: |
          cd lambda  # Garante que estamos no diretório lambda
          npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
